import { StyleSheet } from "@react-pdf/renderer";

const FONT = "NotoSansJP";

export const colors = {
  forest: "#19231B",
  sage: "#8A9668",
  sunset: "#DD9348",
  pebble: "#EDE8E5",
  cream: "#F0EEE9",
  white: "#FFFFFF",
  mist: "#F8F9FA",
  grey: "#6B7280",
  lightGrey: "#E5E7EB",
};

export const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontFamily: FONT,
    fontSize: 10,
    color: colors.forest,
    backgroundColor: colors.white,
  },
  // Header
  headerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 16,
    paddingBottom: 12,
    borderBottomWidth: 2,
    borderBottomColor: colors.sage,
  },
  headerLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  headerLogo: { width: 100, height: 25 },
  brandName: { fontSize: 14, fontFamily: FONT, color: colors.forest },
  brandSub: { fontSize: 8, fontFamily: FONT, color: colors.grey, marginTop: 1 },
  headerRight: { alignItems: "flex-end" },
  docNumber: {
    fontSize: 8,
    fontFamily: FONT,
    color: colors.grey,
    textAlign: "right",
    marginBottom: 2,
  },
  dateText: {
    fontSize: 8,
    fontFamily: FONT,
    color: colors.grey,
    textAlign: "right",
    marginBottom: 2,
  },
  // Title bar
  titleBar: {
    backgroundColor: colors.forest,
    paddingVertical: 10,
    paddingHorizontal: 20,
    marginBottom: 16,
  },
  titleBarText: {
    fontFamily: FONT,
    fontSize: 18,
    color: colors.white,
    textAlign: "center",
    letterSpacing: 4,
  },
  // Client + total row
  clientTotalRow: {
    flexDirection: "row",
    marginBottom: 20,
    gap: 12,
  },
  clientBox: { width: "58%", paddingRight: 12 },
  clientName: {
    fontFamily: FONT,
    fontSize: 14,
    color: colors.forest,
    paddingBottom: 4,
    borderBottomWidth: 1,
    borderBottomColor: colors.forest,
    marginBottom: 8,
  },
  projectLabel: { fontFamily: FONT, fontSize: 9, color: colors.grey, marginBottom: 2 },
  projectName: { fontFamily: FONT, fontSize: 10, color: colors.forest },
  totalBox: {
    width: "40%",
    backgroundColor: colors.cream,
    borderWidth: 1,
    borderColor: colors.sage,
    borderRadius: 4,
    padding: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  totalLabel: { fontFamily: FONT, fontSize: 9, color: colors.grey, marginBottom: 4 },
  totalAmount: { fontFamily: FONT, fontSize: 18, color: colors.forest, marginBottom: 4 },
  totalNote: { fontFamily: FONT, fontSize: 7.5, color: colors.grey },
  // Section
  sectionTitle: {
    fontSize: 12,
    fontFamily: FONT,
    color: colors.forest,
    marginBottom: 8,
    marginTop: 18,
    paddingBottom: 4,
    borderBottomWidth: 1,
    borderBottomColor: colors.sage,
  },
  // Table
  tableHeader: {
    flexDirection: "row",
    backgroundColor: colors.forest,
    paddingVertical: 7,
    paddingHorizontal: 6,
  },
  tableHeaderText: { fontFamily: FONT, fontSize: 8, color: colors.white },
  tableRow: {
    flexDirection: "row",
    paddingVertical: 6,
    paddingHorizontal: 6,
    borderBottomWidth: 0.5,
    borderBottomColor: colors.lightGrey,
  },
  tableRowAlt: {
    flexDirection: "row",
    paddingVertical: 6,
    paddingHorizontal: 6,
    backgroundColor: colors.mist,
    borderBottomWidth: 0.5,
    borderBottomColor: colors.lightGrey,
  },
  cellText: { fontFamily: FONT, fontSize: 8, color: colors.forest, lineHeight: 1.4 },
  colNo: { width: "6%", textAlign: "center" },
  colFeature: { width: "26%" },
  colDetail: { width: "30%" },
  colStandard: { width: "19%", textAlign: "right" },
  colHybrid: { width: "19%", textAlign: "right" },
  totalRow: {
    flexDirection: "row",
    paddingVertical: 8,
    paddingHorizontal: 6,
    backgroundColor: colors.cream,
    borderTopWidth: 2,
    borderTopColor: colors.forest,
  },
  totalRowText: { fontFamily: FONT, fontSize: 9, color: colors.forest },
  // Savings callout
  savingsBox: {
    marginTop: 12,
    padding: 12,
    backgroundColor: "#FEF3E2",
    borderRadius: 4,
    borderLeftWidth: 3,
    borderLeftColor: "#DD9348",
  },
  savingsTitle: { fontFamily: FONT, fontSize: 11, color: colors.sunset, marginBottom: 4 },
  savingsDetail: { fontFamily: FONT, fontSize: 9, color: colors.forest, lineHeight: 1.5 },
  // Body text
  bodyText: {
    fontSize: 9,
    fontFamily: FONT,
    lineHeight: 1.6,
    color: colors.forest,
    marginBottom: 6,
  },
  // List
  listItem: { flexDirection: "row", marginBottom: 4, paddingLeft: 8 },
  listBullet: { width: 16, fontSize: 9, fontFamily: FONT, color: colors.sage },
  listContent: { flex: 1, fontSize: 9, fontFamily: FONT, lineHeight: 1.5 },
  // Disclaimer
  disclaimer: {
    marginTop: 24,
    padding: 12,
    backgroundColor: colors.mist,
    borderRadius: 4,
    fontSize: 8,
    fontFamily: FONT,
    color: colors.grey,
    lineHeight: 1.5,
  },
  // Footer
  footer: {
    position: "absolute",
    bottom: 30,
    left: 40,
    right: 40,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingTop: 8,
    borderTopWidth: 0.5,
    borderTopColor: colors.lightGrey,
  },
  footerText: { fontSize: 7, fontFamily: FONT, color: colors.grey },
});
